### ISSUE TITLE
Add correctly formatted authors with `INBOmd::add_author()`.

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolhelper#117]
- Add correctly formatted authors with `INBOmd::add_author()`.

_Originally posted by @ThierryO in https://github.com/inbo/protocolhelper/issues/112#issuecomment-1731291929_

**Comment by hansvancalster** [comment]
This is part of the list of things that need to be done to enable a protocol-specific zenodo doi (see #112). 
I would like to use the same author format as used by INBOmd for INBO protocols.
Currently, `create_protocol()` will add authors as follows in the yaml:

```
---
author:
- name: 
  orcid: 
- name: 
  orcid: 
---
```

This should become:

```
---
author: 
  - name:
      given: 
      family: 
    email: 
    orcid: 
    affiliation:
    corresponding: 
  - name:
      given: 
      family: 
    email: 
    orcid: 
    affiliation:
    corresponding: 
---
```

Preferably, the same should be applied to reviewers and project_manager as well (see ?create_protocol).
When this is implemented, several unit tests will break and need to be adapted accordingly as well. Also `check_frontmatter` will likely fail (see https://github.com/inbo/protocolhelper/issues/112#issuecomment-1731291929 for further info how to deal with this).
@pietervsd if you have time to dive into this, that would be much appreciated. Preferably via a branch that starts from the next-version branch.
